"""add_is_superuser_to_reseller

Revision ID: 0383e4d2cf4a
Revises: 9ab4579ab457
Create Date: 2025-06-03 18:20:14.792655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0383e4d2cf4a'
down_revision: Union[str, None] = '9ab4579ab457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller_profile', sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_profile', 'is_superuser')
    # ### end Alembic commands ###
