"""create_commission_table

Revision ID: 7a629e8e322e
Revises: 9b19866ce0f0
Create Date: 2025-06-03 19:24:57.514745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a629e8e322e'
down_revision: Union[str, None] = '9b19866ce0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_package_id_at_sale', sa.Integer(), nullable=False),
    sa.Column('original_order_reseller_id', sa.Integer(), nullable=True),
    sa.Column('commission_status', sa.String(length=50), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['original_order_reseller_id'], ['reseller_profile.id'], ),
    sa.ForeignKeyConstraint(['product_package_id_at_sale'], ['product_package.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_commission_status'), 'commission', ['commission_status'], unique=False)
    op.create_index(op.f('ix_commission_commission_type'), 'commission', ['commission_type'], unique=False)
    op.create_index(op.f('ix_commission_id'), 'commission', ['id'], unique=False)
    op.create_index(op.f('ix_commission_order_id'), 'commission', ['order_id'], unique=False)
    op.create_index(op.f('ix_commission_original_order_reseller_id'), 'commission', ['original_order_reseller_id'], unique=False)
    op.create_index(op.f('ix_commission_reseller_id'), 'commission', ['reseller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_reseller_id'), table_name='commission')
    op.drop_index(op.f('ix_commission_original_order_reseller_id'), table_name='commission')
    op.drop_index(op.f('ix_commission_order_id'), table_name='commission')
    op.drop_index(op.f('ix_commission_id'), table_name='commission')
    op.drop_index(op.f('ix_commission_commission_type'), table_name='commission')
    op.drop_index(op.f('ix_commission_commission_status'), table_name='commission')
    op.drop_table('commission')
    # ### end Alembic commands ###
