"""create_product_package_table

Revision ID: 9ab4579ab457
Revises: 7b86da5f06fa
Create Date: 2025-06-03 18:17:28.189529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab4579ab457'
down_revision: Union[str, None] = '7b86da5f06fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('direct_commission_rate_or_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('recruitment_commission_rate_or_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_package_country_code'), 'product_package', ['country_code'], unique=False)
    op.create_index(op.f('ix_product_package_id'), 'product_package', ['id'], unique=False)
    op.create_index(op.f('ix_product_package_name'), 'product_package', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_package_name'), table_name='product_package')
    op.drop_index(op.f('ix_product_package_id'), table_name='product_package')
    op.drop_index(op.f('ix_product_package_country_code'), table_name='product_package')
    op.drop_table('product_package')
    # ### end Alembic commands ###
