"""create_order_table

Revision ID: 9b19866ce0f0
Revises: 0383e4d2cf4a
Create Date: 2025-06-03 18:23:30.192682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b19866ce0f0'
down_revision: Union[str, None] = '0383e4d2cf4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('product_package_id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_paid', sa.String(length=3), nullable=False),
    sa.Column('duration_days_at_purchase', sa.Integer(), nullable=False),
    sa.Column('country_code_at_purchase', sa.String(length=2), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('esim_provisioning_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_package_id'], ['product_package.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_email'), 'order', ['customer_email'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_order_status'), 'order', ['order_status'], unique=False)
    op.create_index(op.f('ix_order_stripe_payment_intent_id'), 'order', ['stripe_payment_intent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_stripe_payment_intent_id'), table_name='order')
    op.drop_index(op.f('ix_order_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_customer_email'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
